on: [push]

jobs:
  gist-sync:
    name: gist-sync
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: popsiclestick/gist-sync-action@v1.2.0
        id: sync
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gist_url: https://gist.github.com/incrypto32/ec7d74ea496599014bb8ed34d0d706f9
          gist_title: eth_resources.md
          gist_description: A curated list of learning resource for blockchain development
          github_file: README.md
